'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Waves,Fish,GraduationCap,Leaf,Pause,Play,Database,Droplets,Activity} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {policies} from '@/data/site';
export const icons={Waves,Fish,GraduationCap,Leaf};
export function PolicyIcon({name,size=28}:{name:string;size?:number}){const Icon=icons[name as keyof typeof icons]||Waves;return <Icon size={size}/>}
export function OceanHero(){const[paused,setPaused]=useState(false);return <section id="home" className={`hero ${paused?'paused':''}`}><img className="hero-art" src="/ocean.png" width="1672" height="941" fetchPriority="high" alt="ภาพสร้างสรรค์สามมิติของเกาะหินปูน ทะเลอันดามัน เรือประมง และป่าชายเลน เชื่อมด้วยเส้นข้อมูล"/><div className="hero-shade"/><div className="container hero-copy"><div className="eyebrow"><span className="dot"/> GP6 • นบส.1 รุ่นที่ 104</div><h1>กระบี่โมเดล<span>สร้างคุณค่าจากทะเล</span>สู่อนาคตที่ยั่งยืน</h1><p>ข้อเสนอการบริหารจัดการชายฝั่งทะเลแบบบูรณาการ<br/>เชื่อมทรัพยากร ผู้คน และนวัตกรรม<br/>เพื่อเศรษฐกิจสีน้ำเงินและการท่องเที่ยวคุณค่าสูง</p><div className="actions"><a className="button" href="#model">สำรวจกระบี่โมเดล <ArrowUpRight size={19}/></a><a className="text-link" href="/documents">อ่านรายงานฉบับเต็ม <ArrowUpRight size={17}/></a></div><span className="hero-study">ผลงานการศึกษาและข้อเสนอเชิงนโยบายของกลุ่ม GP6</span></div><div className="hero-caption"><span>AN OCEAN OF<br/><b>SHARED VALUE</b></span><span className="caption-line"/><small>ภาพสร้างสรรค์เชิงแนวคิด</small></div><div className="hero-bottom container"><span>สมดุลเศรษฐกิจ <i/> ดูแลระบบนิเวศ <i/> แบ่งปันประโยชน์</span><button className="motion-button" onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'เล่นภาพเคลื่อนไหว':'หยุดภาพเคลื่อนไหว'}</button></div></section>}
export function ModelExplorer(){const[selected,setSelected]=useState(0);const p=policies[selected];return <div className="model-explorer"><div className="value-flow" aria-label="เลือกองค์ประกอบกระบี่โมเดล">{policies.map((p,i)=><button key={p.slug} className={selected===i?'selected':''} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span className="flow-icon"><PolicyIcon name={p.icon}/></span><small>{p.number}</small><strong>{p.short}</strong>{i<3&&<ArrowRight className="flow-arrow" size={19}/>}</button>)}</div><div className="model-detail" aria-live="polite"><div><span className="eyebrow">{p.english}</span><h3>{p.title}</h3><p>{p.summary}</p></div><a href={`/policies/${p.slug}`} className="round-link" aria-label={`อ่านนโยบาย ${p.title}`}><ArrowUpRight/></a></div><div className="return-flow"><span>↳</span> รายได้ชุมชนและการดูแลทรัพยากรอย่างต่อเนื่อง <span>↰</span></div></div>}
const panels=[{id:'environment',name:'สิ่งแวดล้อม',icon:Droplets,metrics:[['558','ตันต่อวัน','ขยะมูลฝอยเฉลี่ย','ปี 2567'],['45.2','%','ขยะที่กำจัดอย่างถูกต้อง','ปี 2567']],missing:['คุณภาพน้ำรายพื้นที่','สถานภาพหญ้าทะเลและระบบนิเวศ'],note:'ปริมาณขยะและสัดส่วนการกำจัดเป็นข้อมูลคนละตัวชี้วัด จึงควรอ่านร่วมกันเพื่อเห็นทั้งภาระและความสามารถในการจัดการ'}, {id:'tourism',name:'การท่องเที่ยว',icon:Waves,metrics:[['6.38','ล้านคน','ผู้เยี่ยมเยือน','ปี 2568'],['105,016','ล้านบาท','รายได้จากการท่องเที่ยวโดยประมาณ','ปี 2568']],missing:['ความหนาแน่นเทียบกับขีดความสามารถในการรองรับ'],note:'ตามรายงาน มีที่พักได้รับอนุญาต 908 แห่ง ณ สิงหาคม 2569 โดยร้อยละ 87.5 อยู่ในอำเภอเมืองกระบี่และอำเภอเกาะลันตา'}, {id:'community',name:'ประมงและชุมชน',icon:Fish,metrics:[],missing:['มูลค่าผลิตภัณฑ์ประมงหลังยกระดับ','สัดส่วนการจัดซื้อสินค้าท้องถิ่น','สัดส่วนรายได้ที่เข้าสู่ชุมชน'],note:'รายงานเสนอให้ติดตามการสร้างมูลค่าและการแบ่งปันประโยชน์ ตัวชี้วัดในส่วนนี้ยังไม่มีค่าผลลัพธ์ในรายงาน'}, {id:'skills',name:'แรงงาน',icon:GraduationCap,metrics:[['2,561','คน','ผู้ผ่านการฝึกยกระดับฝีมือแรงงาน','ปี 2568']],missing:['รายได้แรงงานหลังพัฒนาทักษะ','ความก้าวหน้าในอาชีพหลังรับรองสมรรถนะ'],note:'จำนวนผู้ผ่านการฝึกเป็นผลผลิตของกิจกรรม ไม่ใช่หลักฐานว่ารายได้เพิ่มขึ้น จึงต้องติดตามคุณภาพงานและรายได้ต่อไป'}];
export function Dashboard(){return <div className="dashboard dark"><div className="dashboard-heading"><div><span className="eyebrow"><Database size={16}/> KRABI MARINE LINK</span><h3>Blue Economy Dashboard</h3></div><span className="concept-badge">ต้นแบบแนวคิด</span></div><p className="dashboard-intro">ตัวอย่างการติดตามตัวชี้วัดตามรายงาน GP6</p><Tabs defaultValue="environment"><TabsList className="dashboard-tabs" aria-label="หมวดข้อมูล">{panels.map(p=><TabsTrigger key={p.id} value={p.id}><p.icon size={16}/>{p.name}</TabsTrigger>)}</TabsList>{panels.map(p=><TabsContent key={p.id} value={p.id} className="dashboard-panel"><div className="dashboard-metrics">{p.metrics.map(([value,unit,label,year])=><article key={label}><div className="dash-value">{value}<small>{unit}</small></div><p>{label}</p><span className="source">{year} • ตามรายงาน GP6 บทที่ 1</span></article>)}</div><div className="missing-metrics">{p.missing.map(m=><div key={m}><span><Activity size={16}/>{m}</span><small>ยังไม่มีข้อมูลในรายงาน</small></div>)}</div><p className="dashboard-note">{p.note}</p></TabsContent>)}</Tabs><div className="dashboard-footer"><span className="dot"/> ข้อมูลอ้างอิงจากรายงาน • ไม่ใช่ข้อมูลเรียลไทม์</div></div>}
